# Generated by Django 4.1.2 on 2022-10-22 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cve_number",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cve", models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name="Description",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Target",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Incident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("bruteforce", "Bruteforce attack"),
                            ("phishing", "Phishing attack"),
                            ("man_middle", "Man in the middle attack"),
                            ("sql_injectin", "SQL injection attack"),
                        ],
                        max_length=100,
                    ),
                ),
                ("cve_number", models.ManyToManyField(to="api.cve_number")),
                (
                    "description",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.description",
                    ),
                ),
                (
                    "object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.target"
                    ),
                ),
            ],
            options={
                "ordering": ["time_creation"],
            },
        ),
    ]
